import datetime

mockTeams = [
    {"id": "1", "name": "CyberSamurai", "score": 1250, "rank": 1},
    {"id": "2", "name": "RedDragon", "score": 1180, "rank": 2},
    {"id": "3", "name": "PhoenixTeam", "score": 1050, "rank": 3},
    {"id": "4", "name": "DigitalKnights", "score": 920, "rank": 4},
    {"id": "5", "name": "EagleEye", "score": 850, "rank": 5},
    {"id": "6", "name": "NordicHackers", "score": 780, "rank": 6},
    {"id": "7", "name": "TechNinjas", "score": 720, "rank": 7},
    {"id": "8", "name": "CyberBears", "score": 650, "rank": 8},
    {"id": "9", "name": "MapleHackers", "score": 580, "rank": 9},
    {"id": "10", "name": "GarudaGuards", "score": 520, "rank": 10},
    {"id": "11", "name": "AlpinePrecision", "score": 460, "rank": 11},
    {"id": "12", "name": "DesertStorm", "score": 400, "rank": 12},
]

mockActivity = [
{
    "id": "3",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=60),
    "team": "Mh0c473",
    "action": "captured",
    "question_id": "4",
},
{
    "id": "4",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=90),
    "team": "RedDragon",
    "action": "captured",
    "question_id": "1",
},
{
    "id": "5",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=120),
    "team": "Punina",
    "action": "captured",
    "question_id": "3",
},
{
    "id": "7",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=11180),
    "team": "AyamKunyit",
    "action": "captured",
    "question_id": "5",
},
{
    "id": "9",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1112240),
    "team": "PhoenixTeam",
    "action": "captured",
    "question_id": "7",
},
{
    "id": "11",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=360),
    "team": "TechNinjas",
    "action": "captured",
    "question_id": "6",
},
{
    "id": "13",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=480),
    "team": "EagleEye",
    "action": "captured",
    "question_id": "8",
},
{
    "id": "16",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=660),
    "team": "TequilaTeam",
    "action": "captured",
    "question_id": "9",
},
{
    "id": "18",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=780),
    "team": "KangarooKrew",
    "action": "captured",
    "question_id": "10",
},
{
    "id": "20",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=900),
    "team": "TulipTactics",
    "action": "captured",
    "question_id": "11",
},
{
    "id": "23",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1080),
    "team": "AlpinePrecision",
    "action": "captured",
    "question_id": "12",
},
{
    "id": "25",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1200),
    "team": "NollywoodNet",
    "action": "captured",
    "question_id": "13",
},
{
    "id": "27",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1320),
    "team": "CyberSamurai",
    "action": "captured",
    "question_id": "14",
},
{
    "id": "29",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1440),
    "team": "DiamondDiggers",
    "action": "captured",
    "question_id": "15",
},
{
    "id": "31",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1560),
    "team": "EiffelEncrypters",
    "action": "captured",
    "question_id": "16",
},
{
    "id": "34",
    "timestamp": datetime.datetime.now() - datetime.timedelta(seconds=1740),
    "team": "OilRigRaiders",
    "action": "captured",
    "question_id": "17",
},
]