name: Deploy Backend on Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Run pre-deploy tests (edit as per your codebase)
      - name: Run pre-deployment tests
        run: |
          echo "Running tests..."
          python -m unittest discover -s tests || exit 1

      # 3. Setup SSH for deployment
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 4. SSH into VM and pull latest code
      - name: SSH into GCP VM and update app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/YOUR_REPO_FOLDER  # Replace with correct path
            echo "Pulling latest code..."
            git pull origin main
            echo "Restarting Docker Compose..."
            docker compose down
            docker compose up --build -d
          EOF

      # 5. Health check: test backend API is up
      - name: Check API Health
        run: |
          echo "Checking backend health at https://api-obscura.ccstiet.com/test"
          curl --fail --retry 5 --retry-delay 3 https://api-obscura.ccstiet.com/test
